
["Centrifuge Tiers Reproduced Options"]
	#
	#High End Centrifuge Speed
	#Range: > 1
	highEndCentrifugeSpeed = 4
	#
	#High End Centrifuge Item Max Stack Size
	#Range: > 1
	highEndCentrifugeItemMaxStackSize = 256
	#
	#High End Centrifuge Output Multiplier
	#Range: > 1
	highEndCentrifugeOutputMultiplier = 2
	#
	#High End Centrifuge Energy Capacity
	#Range: > 1
	highEndCentrifugeEnergyCapacity = 100000
	#
	#High End Centrifuge Fluid Capacity
	#Range: > 1
	highEndCentrifugeFluidCapacity = 100000
	#
	#Nuclear Centrifuge Speed
	#Range: > 1
	nuclearCentrifugeSpeed = 5
	#
	#Nuclear Centrifuge Item Max Stack Size
	#Range: > 1
	nuclearCentrifugeItemMaxStackSize = 512
	#
	#Nuclear Centrifuge Output Multiplier
	#Range: > 1
	nuclearCentrifugeOutputMultiplier = 4
	#
	#Nuclear Centrifuge Energy Capacity
	#Range: > 1
	nuclearCentrifugeEnergyCapacity = 200000
	#
	#Nuclear Centrifuge Fluid Capacity
	#Range: > 1
	nuclearCentrifugeFluidCapacity = 200000
	#
	#Cosmic Centrifuge Speed
	#Range: > 1
	cosmicCentrifugeSpeed = 7
	#
	#Cosmic Centrifuge Item Max Stack Size
	#Range: > 1
	cosmicCentrifugeItemMaxStackSize = 1024
	#
	#Cosmic Centrifuge Output Multiplier
	#Range: > 1
	cosmicCentrifugeOutputMultiplier = 8
	#
	#Cosmic Centrifuge Energy Capacity
	#Range: > 1
	cosmicCentrifugeEnergyCapacity = 600000
	#
	#Cosmic Centrifuge Fluid Capacity
	#Range: > 1
	cosmicCentrifugeFluidCapacity = 600000
	#
	#Creative Centrifuge Item Max Stack Size
	#Range: > 1
	creativeCentrifugeItemMaxStackSize = 16384
	#
	#Creative Centrifuge Output Multiplier
	#Range: > 1
	creativeCentrifugeOutputMultiplier = 100
	#
	#Creative Centrifuge Fluid Capacity
	#Range: > 1
	creativeCentrifugeFluidCapacity = 2147483647

